language: go

go:
  - 1.8.x

services:
  - docker

before_install:
  - VERSION=${TRAVIS_TAG:1}
  - make init

script:
  - make stylecheck
  - make lint
  - make test
  - make build-all
  - make test-integration
  - make package-init
  - make package
  - make docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make docker-push;
    fi
  - if [ ! -z "$TRAVIS_TAG" ]; then
    docker tag $DOCKER_USERNAME/visualization-api $DOCKER_USERNAME/visualization-api:${TRAVIS_TAG:1};
    docker push $DOCKER_USERNAME/visualization-api:${TRAVIS_TAG:1};
    fi
